### ISSUE TITLE
Couple Questions

### ISSUE THREAD

**Issue by osabate** [mordadam/google-translate-html-js#2]
Thanks for building this and making it open and free for people to use.

Questions:
1. Can this plugin translate web apps? So once the user makes a language selection, it persist it through its entire session.
2. Does it translate modals / dialog boxes and content loaded asynchronously?

**Comment by mordadam** [comment]
Thank you very much for your attention!

1. Currently we do not have such a possibility, but in the next update I will try to cover this issue somehow.
2. Everything that is seen on the page as text will be translated.

**Comment by osabate** [comment]
Great! Looking forward to it. Thank you :)

**Comment by mordadam** [comment]
Thank you for your feedback :)
